// ─── ABIs ─────────────────────────────────────────────────────────────────────
// Six router ABI variants:
//   BASE_ROUTER_ABI              — shared functions, no native swap
//   PLS_ROUTER_ABI               — PulseChain native swap functions
//   ETH_ROUTER_ABI               — ETH-native chains' swap functions
//   BASE_INTEGRATOR_ROUTER_ABI   — BASE + _integratorId on swapNoSplit
//   PLS_INTEGRATOR_ROUTER_ABI    — PLS + _integratorId on native swaps
//   ETH_INTEGRATOR_ROUTER_ABI    — ETH + _integratorId on native swaps

// eslint-disable-next-line @typescript-eslint/no-require-imports
const abiData = require("./abi_data.json") as {
  BASE_ROUTER_ABI: object[];
  PLS_ROUTER_ABI: object[];
  ETH_ROUTER_ABI: object[];
  ERC20_ABI: object[];
};

export const BASE_ROUTER_ABI: object[] = abiData.BASE_ROUTER_ABI;
export const PLS_ROUTER_ABI: object[]  = abiData.PLS_ROUTER_ABI;
export const ETH_ROUTER_ABI: object[]  = abiData.ETH_ROUTER_ABI;
export const ERC20_ABI: object[]       = abiData.ERC20_ABI;

// ─── Integrator (on-chain affiliate) ABI variants ─────────────────────────────
// Generated by adding _integratorId (bytes32) param to each swap function.
// These are identical to the standard ABIs except each swap function receives
// an extra trailing parameter so the on-chain router can attribute the trade.

const INTEGRATOR_ID_INPUT = {
  name: "_integratorId",
  internalType: "bytes32",
  type: "bytes32",
};

const INTEGRATOR_SWAP_NAMES = new Set([
  "swapNoSplit",
  "swapNoSplitFromPLS", "swapNoSplitToPLS",
  "swapNoSplitFromETH", "swapNoSplitToETH",
]);

function addIntegratorParam(abiEntry: any): any {
  if (
    abiEntry?.type === "function" &&
    INTEGRATOR_SWAP_NAMES.has(abiEntry.name)
  ) {
    return { ...abiEntry, inputs: [...abiEntry.inputs, INTEGRATOR_ID_INPUT] };
  }
  return abiEntry;
}

export const BASE_INTEGRATOR_ROUTER_ABI: object[] =
  BASE_ROUTER_ABI.map(addIntegratorParam);

export const PLS_INTEGRATOR_ROUTER_ABI: object[] =
  PLS_ROUTER_ABI.map(addIntegratorParam);

export const ETH_INTEGRATOR_ROUTER_ABI: object[] =
  ETH_ROUTER_ABI.map(addIntegratorParam);
